
                <tr class="tr_white">                                            
                    <td align="center">[field:title /]</td>   
                    <td align="center" height="28">
                        [field:width/]×[field:height/]
                    </td>    
                    <td align="center">
                        <input type="button" onclick="window.location.href = 'vrpano_cube_edit.php?id=[field:id /]&page=[field:page /]';" value="修改" class="btn1"/>
                        <input type="button" onclick="window.location.href = 'vrpano_cube_del.php?id=[field:id /]';" value="删除" class="btn1"/>
                    </td>
                </tr>
                