
                <tr align="center" class="tr_white">
                    <td height="30">[field:rank/]</td>
                    <td height="30">[field:typename/]</td>
                    <td>
                        <input type="button" onclick="window.location.href='sys_group_edit.php?rank=[field:rank/]'" value="权限设定" class="btn1"/>
                    </td>
                </tr>
                