<?php  exit();
/*
Page: /
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-05-05 03:11:57
*/
?>
<?php  exit();
/*
Page: /
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-05-05 03:12:15
*/
?>
<?php  exit();
/*
Page: /admin/sys_data.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-05-24 03:17:15
*/
?>
<?php  exit();
/*
Page: /admin/sys_data.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-05-24 03:17:18
*/
?>
<?php  exit();
/*
Page: /admin/sys_info.php
Error: 错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2013-05-24 03:17:19
*/
?>
